config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  get '/paginas', to: 'static_pages#pagina'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :towers
  resources :apartments
  resources :people
end

app/models/apartment.rb
class Apartment < ApplicationRecord
	has_many :people
	belongs_to :tower
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
	belongs_to :apartment
end

app/models/tower.rb
class Tower < ApplicationRecord
	has_many :apartments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController

	before_action :set_apartment, only: [:show, :update, :edit, :destroy]	

  	#GET HTTP METHOD
  	def index
  		@apartamentos = Apartment.all
  	end

  	#GET HTTP METOD
  	def new
  		@apartamento = Apartment.new
  	end

  	#POST HTTP METHOD
  	def create
  		@apartamento = Apartment.new(apartments_params)

  		respond_to do |format|
  			if @apartamento.save
  				format.html {redirect_to apartments_path, notice: 'Apartamento guardado en la base de datos'}
				format.json {render :index, status: :created}
			else
				format.html {render :new, notice: 'No se pudo guardar el apartamento, intenta de nuevo'}
				format.json {render json: @apartamento.errors, status: :unprocessable_entity}
			end
  		end	
  	end

  	def show
  	end

  	def edit
  	end

  	def update
  		respond_to do |format|
  			if @apartamento.update(apartments_params)
  				format.html {redirect_to apartments_path, notice: 'Apartamento fue actualizado' }
  				format.json {render :show, status: :ok}
  			else
  				format.html {render :edit}
  				format.json {render json: @apartamento.errors, status: :unprocessable_entity}
  			end
  		end
  	end

  	def destroy
  		@apartamento.destroy
  		respond_to do |format|
  			format.html {redirect_to apartments_path, notice: 'Apartamento fue borrado'}
  			format.json {head :no_contents }
  		end
  	end






  	private
  	
  	def set_apartment
  		@apartamento = Apartment.find(params[:id])
  	end

  	def apartments_params
  		params.require(:apartment).permit(:nombre, :torre, :piso)
  	end








end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
  	paginas_path
  end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController

	before_action :set_person, only: [:show, :edit, :update, :destroy]
	#GET HTTP METHOD
	def index
		@personas = Person.all 
	end


	#GET HTTP METOD
	def new
		@persona = Person.new
	end

	#POST HTTP METHOD
	def create
		@persona = Person.new(people_params)
		respond_to do |format|
			if @persona.save
				format.html {redirect_to people_path, notice: 'Persona guardada en la base de datos'}
				format.json {render :index, status: :created}
				
			else 
				format.html {render :new, notice: 'no se pudo guardar, intenta de nuevo'}
				format.json {render json: @personas.errors, status: :unprocessable_entity}
			end
		end
	end


	def show
	end

	def edit
	end

	def update
		respond_to do |format|
			if @persona.update(people_params)
				format.html {redirect_to people_path, notice: 'Persona fue actualizada'}
				format.json {render index, status: :ok}
			else
				format.html {render :edit, notice: 'No se pudo actualizar, intenta de nuevo'}
				format.json {render json: @persona.errors, status: :unprocessable_entity}
			end
		end
	end

	def destroy
		@persona.destroy
		respond_to do |format|
			format.html {redirect_to people_path, notice: 'Persona fue borrada'}
			format.jsom {head :no_contents}
		end
	end




	private
	def set_person
		@persona = Person.find(params[:id])
	end


	def people_params
		params.require(:person).permit(:name, :identificacion, :apartamento)
	end



end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def pagina

  end
  
end

app/controllers/towers_controller.rb
class TowersController < ApplicationController

	before_action :set_tower, only: [:show, :update, :edit, :destroy]	

  	#GET HTTP METHOD
  	def index
  		@torres = Tower.all
  	end

  	#GET HTTP METOD
  	def new
  		@torre = Tower.new
  	end

  	#POST HTTP METHOD
  	def create
  		@torre = Tower.new(towers_params)

  		respond_to do |format|
  			if @torre.save
  				format.html {redirect_to towers_path, notice: 'Torre guardada en la base de datos'}
				  format.json {render :index, status: :created}
			  else
				  format.html {render :new, notice: 'No se pudo guardar la torre, intenta de nuevo'}
				  format.json {render json: @torre.errors, status: :unprocessable_entity}
			  end
  		end	
  	end

  	def show
  	end

  	def edit
  	end

  	def update
  		respond_to do |format|
  			if @torre.update(towers_params)
  				format.html {redirect_to towers_path, notice: 'Torre fue actualizada' }
  				format.json {render :show, status: :ok}
  			else
  				format.html {render :edit}
  				format.json {render json: @torre.errors, status: :unprocessable_entity}
  			end
  		end
  	end

  	def destroy
  		@torre.destroy
  		respond_to do |format|
  			format.html {redirect_to towers_path, notice: 'Torre fue borrada'}
  			format.json {head :no_contents }
  		end
  	end






  	private
  	
  	def set_tower
  		@torre = Tower.find(params[:id])
  	end

  	def towers_params
  		params.require(:tower).permit(:nombre, :portero)
  	end


end

app/helpers/apartments_helper.rb
module ApartmentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/towers_helper.rb
module TowersHelper
end

app/views/apartments/index.html.erb
<h1>Lista de todos los Apartamentos</h1>

<table>
	<!-- <caption>table title and/or explanatory text</caption> -->
	<thead>
		<tr>
			<th>Nombre</th>
			<th>Torre</th>
			<th>Piso</th>
		</tr>
	</thead>
	<tbody>
		<!-- Solo EJECUTAR se utiliza <% %> -->
		<!-- MOSTRAR y EJECUTAR se utiliza <%= %> -->
		<% @apartamentos.each do |x| %>
		<tr>
			<td><%=x.nombre%></td>
			<td><%=x.torre%></td>
			<td><%=x.piso%></td>
			<td><%= link_to 'Ver datos del Apartamento', apartment_path(x) %></td>
		</tr>
		<%end%>
	</tbody>
</table>

app/views/apartments/new.html.erb
<%=form_for(@apartamento) do |i|%>
	<h2>Ingrese los datos del Apartamento</h2>
	<div>
		<%= i.label :nombre%>
		<%= i.text_field :nombre%>
	</div>
	<br>
	<div>
		<%= i.label :torre%>
		<%= i.text_field :torre%>
	</div>
	<br>
	<div>
		<%= i.label :piso%>
		<%= i.text_field :piso%>
	</div>
	<br>
	<div>
		<%= i.submit%>
	</div>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ejercicio</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/index.html.erb
<h1>Lista de todas las Personas</h1>

<table>
	<!-- <caption>table title and/or explanatory text</caption> -->
	<thead>
		<tr>
			<th>Nombre</th>
			<th>Identificacion</th>
			<th>Apartamento</th>
		</tr>
	</thead>
	<tbody>
		<!-- Solo EJECUTAR se utiliza <% %> -->
		<!-- MOSTRAR y EJECUTAR se utiliza <%= %> -->
		<% @personas.each do |x| %>
		<tr>
			<td><%=x.nombre%></td>
			<td><%=x.identificacion%></td>
			<td><%=x.apartamento%></td>
			<td><%= link_to 'Ver datos de la persona', person_path(x) %></td>
		</tr>
		<%end%>
	</tbody>
</table>

app/views/people/new.html.erb
<%=form_for(@persona) do |i|%>
	<h2>Ingrese los datos de la Persona</h2>
	<div>
		<%= i.label :nombre%>
		<%= i.text_field :nombre%>
	</div>
	<br>
	<div>
		<%= i.label :identificacion%>
		<%= i.text_field :identificacion%>
	</div>
	<br>
	<div>
		<%= i.label :apartamento%>
		<%= i.text_field :apartamento%>
	</div>
	<br>
	<div>
		<%= i.submit%>
	</div>
<%end%>

app/views/static_pages/pagina.html.erb
<% if user_signed_in? %>
  <li>
  <%= link_to('Cerrar Sesion', destroy_user_session_path, :method => :delete) %>        
  </li>
<% else %>
  <li>
  <%= link_to('Iniciar Sesion', new_user_session_path)  %>  
  </li>
<% end %>

<h1>BIENVENIDO A MI PAGINA WEB </h1>

app/views/towers/index.html.erb
<h1>Lista de todas las Torres</h1>

<table>
	<!-- <caption>table title and/or explanatory text</caption> -->
	<thead>
		<tr>
			<th>Nombre</th>
			<th>Portero</th>
		</tr>
	</thead>
	<tbody>
		<!-- Solo EJECUTAR se utiliza <% %> -->
		<!-- MOSTRAR y EJECUTAR se utiliza <%= %> -->
		<% @torres.each do |torre| %>
		<tr>
			<td><%=torre.nombre%></td>
			<td><%=torre.portero%></td>
			<td><%= link_to 'Ver datos de la Torre', tower_path(torre) %></td>
		</tr>
		<%end%>
	</tbody>
</table>

app/views/towers/new.html.erb
<%=form_for(@torre) do |i|%>
	<h2>Ingrese los datos de la Torre</h2>
	<div>
		<%= i.label :nombre%>
		<%= i.text_field :nombre%>
	</div>
	<br>
	<div>
		<%= i.label :portero%>
		<%= i.text_field :portero%>
	</div>
	<br>
	<div>
		<%= i.submit%>
	</div>
<%end%>